version: "3"
services:
  backend:
    build: ./backend
    container_name: api_backend
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend/my-app
    container_name: api_frontend
    ports:
      - "8020:8020"
